spring:
  datasource:
    url: jdbc:sqlserver://cybermediadb.database.windows.net:1433;database=survery;user=vmadmin@cybermediadb;password=Sup33rman123#;encrypt=true;trustservercertificate=false;hostnameincertificate=*.database.windows.net;loginTimeout=30;
    username: vmadmin
    password: Sup33rman123#

  jms:
    servicebus:
      connection-string: Endpoint=sb://cybermedia-springboot.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Y5ru5oN9YDZpc7d94RS2Cd6cAa+fEzzsm3Eb3h/RUWI=
      idle-timeout: 20000
      pricing-tier: basic

  zipkin:
    sender:
      type: web
      
  sleuth:
    sampler:
      probability: 1
      
azure:
  application-insights:
    instrumentation-key: InstrumentationKey=5c2fa6bb-f36d-43df-89fb-f25c1e24e13b;IngestionEndpoint=https://eastus2-0.in.applicationinsights.azure.com/
